/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-03-14 21:57:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;
import quiz.*;
import java.text.*;
import database.*;
import util.*;

public final class EditQuestionSummary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");

MyQuiz myquiz = new MyQuiz(request.getParameter("quizID"), 1);
//MyQuiz myquiz = new MyQuiz("Q1",1);
List<Question> questionList = myquiz.getQuestionList();

      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("    <link rel=\"icon\" href=\"/favicon.ico\">\n");
      out.write("\n");
      out.write("    <title>Edit Questions</title>\n");
      out.write("    <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <link href=\"./css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"site-wrapper\">\n");
      out.write("      <a href=\"./homepage.jsp\"><div class=\"site-logo\"></div></a>\n");
      out.write("\t  <div class=\"quiz-background\">\n");
      out.write("<h4>Step2: You can select ANY of the following question you want to edit!</h4>\n");
      out.write("\n");
      out.write("<table style=\"width:100%\">\n");
      out.write("  <tr>\n");
      out.write("    <th>Question Index</th>\n");
      out.write("    <th>Question Type</th>\n");
      out.write("    <th>Question</th>\n");
      out.write("    <th>Button</th>\n");
      out.write("  </tr>\n");

	for (int i = 1; i <= questionList.size(); i++) {
		out.println("<tr>");
		out.println("<td>" + i + "</td>");
		out.println("<td>" + questionList.get(i-1).getType() + "</td>");
		out.println("<td>" + questionList.get(i-1).getQuestion() + "</td>");
		out.println("<td>" + "<form action=\"EditSingleQuestionServlet\" method=\"post\">");
		out.println("<input type=\"hidden\" name=\"quizID\" value=\"" + myquiz.getId() + "\">");
		out.println("<input type=\"hidden\" name=\"questionType\" value=\"" + questionList.get(i-1).getType() + "\">");
		out.println("<input type=\"hidden\" name=\"questionID\" value=\"" + questionList.get(i-1).getId() + "\">");
		out.println("<input type=\"submit\" value=\"edit\"></form>" + "</td>");
		out.println("</tr>");
	}	

      out.write("\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("<hr>\n");
      out.write("If you have finished editing question, please click here to finish! <br>\n");
      out.write("<form action=\"FinishEditQuizServlet\" method=\"post\">\n");
      out.write("<input type=\"hidden\" name=\"quizID\" value=\"");
      out.print(myquiz.getId() );
      out.write("\">\n");
      out.write("<input type=\"submit\" value=\"I'm done!\">\n");
      out.write("</form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
