/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-03-14 21:57:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import quiz.*;
import java.text.*;
import database.*;
import util.*;

public final class EditQuiz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");

MyQuiz myquiz = new MyQuiz(request.getParameter("ID"), 1);
//MyQuiz myquiz = new MyQuiz("Q1",1);

      out.write("\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"utf-8\">\n");
      out.write("    <link rel=\"icon\" href=\"/favicon.ico\">\n");
      out.write("\n");
      out.write("    <title>Edit QUiz</title>\n");
      out.write("    <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <link href=\"./css/style.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"site-wrapper\">\n");
      out.write("      <a href=\"./homepage.jsp\"><div class=\"site-logo\"></div></a>\n");
      out.write("\t  <div class=\"quiz-background\">\n");
      out.write("<h3>You are going to editing this quiz!</h3>\n");
      out.write("<h4>Please review the following quiz information! You can modify any of them if you want!</h4>\n");
      out.write("<form action=\"EditQuizInfoServlet\" method=\"post\">\n");
      out.write("Name: ");
      out.print(myquiz.getQuizName() );
      out.write("<br>\n");
      out.write("Description: <br><textArea name=\"quizDescription\" rows=\"10\" cols=\"60\" >");
      out.print( myquiz.getQuizDescription() );
      out.write("</textarea><br>\n");
      out.write("Tag:<input type=\"text\" name=\"tag\" value=\"");
      out.print( Helper.generateTags(myquiz.getTag()) );
      out.write("\"><br>\n");
      out.write("Category:<select name=\"category\" >\n");
      out.write("  <option value =\"");
      out.print(myquiz.getCategory());
      out.write('"');
      out.write('>');
      out.print(myquiz.getCategory());
      out.write("</option>\n");
      out.write("  <option value =\"Others\">Others</option>\n");
      out.write("  <option value =\"Math\">Math</option>\n");
      out.write("  <option value =\"Science\">Science</option>\n");
      out.write("  <option value=\"History\">History</option>\n");
      out.write("  <option value=\"Phisics\">Physics</option>\n");
      out.write("  <option value =\"Chemistry\">Chemistry</option>\n");
      out.write("  <option value=\"Biology\">Biology</option>\n");
      out.write("  <option value=\"Art\">Art</option>\n");
      out.write("</select><br>\n");
      out.write("\n");

	if (myquiz.isPractice()) {
		out.println("<input type=\"checkbox\" name=\"isPracticeMode\" value=\"isPracticeMode\" checked> Allow Practice Mode");
	} else {
		out.println("<input type=\"checkbox\" name=\"isPracticeMode\" value=\"isPracticeMode\"> Allow Practice Mode");
	}

	if (myquiz.isRandomOrder()) {
		out.println("<input type=\"checkbox\" name=\"isRandomOrder\" value=\"isRandomOrder\"checked> Random Order<br>");
	} else {
		out.println("<input type=\"checkbox\" name=\"isRandomOrder\" value=\"isRandomOrder\"> Random Order<br>");
	}
	
	if (myquiz.isSinglePage()) {
		out.println("<input type=\"checkbox\" name=\"isSinglePage\" value=\"isSinglePage\" checked> All Question in Single Page");
	} else {
		out.println("<input type=\"checkbox\" name=\"isSinglePage\" value=\"isSinglePage\"> All Question in Single Page");
	}
	
	if (myquiz.isCorrection()) {
		out.println("<input type=\"checkbox\" name=\"isCorrection\" value=\"isCorrection\" checked>Immediate Correction<br>");
	} else {
		out.println("<input type=\"checkbox\" name=\"isCorrection\" value=\"isCorrection\">Immediate Correction<br>");
	}

      out.write("\n");
      out.write("<input type=\"hidden\" name=\"quizID\" value=");
      out.print(myquiz.getId());
      out.write(" >\n");
      out.write("<input type=\"submit\" value=\"Edit Question\">\n");
      out.write("</form>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
