/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-03-13 11:30:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.math.BigDecimal;
import Model.MessageModel;
import java.util.ArrayList;
import java.sql.Timestamp;
import java.util.concurrent.TimeUnit;
import java.text.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public final class Inbox_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Inbox</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");

	session = request.getSession();
	String touser = (String) session.getAttribute("username");
	
	MessageModel InboxInfo = new MessageModel(touser); //touser
	ArrayList<MessageModel> InboxList = InboxInfo.GetInboxInfo("puni");
	int total = InboxList.size();

      out.write("\n");
      out.write("\n");
      out.write("<form action=\"InboxServlet\" method=\"post\">\n");
      out.write("    <ul>\n");
      out.write("        ");

        	if(total!=0){
	            for (MessageModel eachmail : InboxList) {
	                out.print(eachmail.fromuser);
	                SimpleDateFormat df = new SimpleDateFormat("YYYY.MM.dd HH:mm:ss");
	        		String s = df.format(eachmail.sent_time);
	
	                if(!eachmail.read) 
	                	out.print(" <a href=" + 
	                	"InboxServlet?emailID=" +
	                	eachmail.emailID_ + "&from=" + eachmail.fromuser + "&to=" + eachmail.touser + "&readornot=" + eachmail.read + ">" + 
	                	"<b>" + eachmail.title + 
	                	"</b>" + "</a> ");
	                else 
	                	out.print(" <a href=" + 
	                	"InboxServlet?emailID=" + 
	                	eachmail.emailID_ + "&from=" + eachmail.fromuser + "&to=" + eachmail.touser + "&readornot=" + eachmail.read + ">" + 
	                	eachmail.title + "</a> ");
	                out.print(s);
	                
	                String combine = eachmail.emailID_ + "," + eachmail.fromuser + "," + eachmail.touser;
	                
	                out.print("<input type=" + "\"radio\"" + " name=" + "\"emailID\" " + "value=" + combine + " />");
	               
	                out.print("<br/>");
	            }
	            out.print(" <input type=submit name=emailID value=delete> <br/>");
        	}
        
      out.write("\n");
      out.write("    </ul>\n");
      out.write("    Total: ");
      out.print( total );
      out.write("\n");
      out.write("</form>\n");
      out.write("\t<a href=\"Mail.jsp\"><input type=\"button\" value=\"Go Back\"/></a>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
