/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-03-14 21:35:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.MessageModel;
import java.util.ArrayList;
import java.math.BigDecimal;
import Model.MessageModel;
import java.util.ArrayList;
import java.sql.Timestamp;
import java.util.concurrent.TimeUnit;
import java.text.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public final class Mail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <link rel=\"icon\" href=\"/favicon.ico\">\n");
      out.write("\n");
      out.write("    <title>Quiz</title>\n");
      out.write("    <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"./css/style.css\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("  </head>\n");
      out.write("<body>\n");
      out.write("\t<body>\n");
      out.write("    <div class=\"site-wrapper\">\n");
      out.write("      <a href=\"homepage.jsp\"><div class=\"site-logo\"></div></a>\n");

	session = request.getSession();
	String touser = (String) session.getAttribute("username");
	String displayName = (String) session.getAttribute("displayname");
	
	MessageModel InboxInfo = new MessageModel(touser); //touser
	ArrayList<MessageModel> InboxList = InboxInfo.GetInboxInfo(touser);
	int total_inbox = InboxList.size();
	
	MessageModel boxInfo = new MessageModel(touser); //fromuser
	ArrayList<MessageModel> SentboxList = boxInfo.GetSentboxInfo(touser);
	int total_sentbox = SentboxList.size();

      out.write("\n");
      out.write("\t\t<div class=\"lpanel lpanel3\">\n");
      out.write("\t\t<div class = \"nav-menu-user\">\n");
      out.write("\t\t<ul>\n");
      out.write("          <li id = \"M1\">\n");
      out.write("              <span class=\"nav-icon-user\" id=\"message\">a</span>\n");
      out.write("              <span class=\"nav-title-user\">Compose</span>\n");
      out.write("          </li>\n");
      out.write("          <li id = \"M2\">\n");
      out.write("            \n");
      out.write("              <span class=\"nav-icon-user\" id=\"quiz\">s</span>\n");
      out.write("              <span class=\"nav-title-user\">Inbox</span>\n");
      out.write("            \n");
      out.write("          </li>\n");
      out.write("          <li id = \"M3\">\n");
      out.write("            \n");
      out.write("             <span class=\"nav-icon-user\" id=\"setting\">u</span>\n");
      out.write("              <span class=\"nav-title-user\">Sent</span>\n");
      out.write("            \n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("\t  </div>\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\t  <div class = \"cpanel-user\" id = \"M2-b\">\n");
      out.write("\t\t  <h1>Inbox</h1>\n");
      out.write("\t\t  \n");
      out.write("\t\t\t\t<form action=\"InboxServlet\" method=\"post\">\n");
      out.write("\t\t\t\t    \t\t    \n");
      out.write("\t\t\t\t        ");

						out.print("<table class = \"table\" id =\"inbox-table\" style=" + "\"width:60%;\"" + ">");
						out.print("<tr>");
						out.print("<th>From</th>");
						out.print("<th>Title</th>");
						out.print("<th>Time</th>");
						out.print("<th>    </th>");
					
				        	if(total_inbox!=0){
					            for (MessageModel eachmail : InboxList) {
					            	out.print("<tr>");
					            	out.print("<td>");
					                out.print(eachmail.fromuser);
					                out.print("</td>");
					                SimpleDateFormat df = new SimpleDateFormat("YYYY.MM.dd HH:mm:ss");
					        		String s = df.format(eachmail.sent_time);
					
					                if(!eachmail.read){ 
					                	out.print("<td>");
					                	out.print(" <a href=" + 
					                	"InboxServlet?emailID=" +
					                	eachmail.emailID_ + "&from=" + eachmail.fromuser + "&to=" + eachmail.touser + "&readornot=" + eachmail.read + ">" + 
					                	"<b>" + eachmail.title +
					                	"</b>" + "</a> ");
					                	out.print("</td>");
					                }
					                else{ 
					                	out.print("<td>");
					                	out.print(" <a href=" + 
					                	"InboxServlet?emailID=" + 
					                	eachmail.emailID_ + "&from=" + eachmail.fromuser + "&to=" + eachmail.touser + "&readornot=" + eachmail.read + ">" + 
					                			"<font color=\"" + "grey\"" + ">" + eachmail.title + "</font>" + "</a> ");
					                	out.print("</td>");
					                }
					                	out.print("<td>");
					                	out.print(s);
					                	out.print("</td>");
					                	
					                String combine = eachmail.emailID_ + "," + eachmail.fromuser + "," + eachmail.touser;
					                
					                out.print("<td>");
					                out.print("<input type=" + "\"radio\"" + " name=" + "\"emailID\" " + "value=" + combine + " />");
					                out.print("</td>");
					                out.print("</tr>");
					                out.print("<br/>");
					            }
					            out.print("</table>");
					            out.print(" <input type=submit name=emailID value=delete> <br/>");
				        	}
				        
      out.write("\n");
      out.write("\t\t\t\t    Total: ");
      out.print( total_inbox );
      out.write("\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t <div class = \"cpanel-user\" id = \"M3-b\">\n");
      out.write("\t\t<h1>Sent</h1>\n");
      out.write("\t\t<form action=\"SentboxServlet\" method=\"post\">\n");
      out.write("\t\t        ");

				
				
		        	if(total_sentbox!=0){
		        		out.print("<table class = \"table\" id =\"sentbox-table\" style=" + "\"width:60%;\"" + ">");
						out.print("<tr>");
						out.print("<th>From</th>");
						out.print("<th>Title</th>");
						out.print("<th>Time</th>");
						out.print("<th>    </th>");
			            for (MessageModel eachmail : SentboxList) {
			            	out.print("<tr>");
			            	out.print("<td>");
			                out.print(eachmail.touser);
			                out.print("</td>");
			                SimpleDateFormat df = new SimpleDateFormat("YYYY.MM.dd HH:mm:ss");
			        		String s = df.format(eachmail.sent_time);
			
			                if(!eachmail.read) {
			                	out.print("<td>");
			                	out.print(" <a href=" + 
			                	"SentboxServlet?emailID=" +
			                	eachmail.emailID_ + "&from=" + eachmail.fromuser + "&to=" + eachmail.touser + "&readornot=" + eachmail.read + ">" + 
			                	"<b>" + eachmail.title + 
			                	"</b>" + "</a> ");
			                	out.print("</td>");
			                }
			                else {
			                	out.print("<td>");
			                	out.print(" <a href=" + 
			                	"SentboxServlet?emailID=" + 
			                	eachmail.emailID_ + "&from=" + eachmail.fromuser + "&to=" + eachmail.touser + "&readornot=" + eachmail.read + ">" + 
			                			"<font color=\"" + "grey\"" + ">" + eachmail.title + "</font>" + "</a> ");
			                	out.print("</td>");
			                }
			                out.print("<td>");
			                	out.print(s);
			                	out.print("</td>");
							String combine = eachmail.emailID_ + "," + eachmail.fromuser + "," + eachmail.touser;
							out.print("<td>");
			                out.print("<input type=" + "\"radio\"" + " name=" + "\"emailID\" " + "value=" + combine + " />");
			                out.print("</td>");
			                out.print("</tr>");
			               out.print("<br/>");
			            }
			            out.print("</table>");
			            out.print(" <input type=submit name=emailID value=delete> <br/>");
		        	}
		        
      out.write("\n");
      out.write("\t\t    Total: ");
      out.print( total_sentbox );
      out.write("\n");
      out.write("\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class = \"cpanel-user\" id = \"M1-b\">\n");
      out.write("\t\t\t<h4>Compose</h4>\n");
      out.write("\t\t\t<form action=\"ComposeServlet\" method=\"post\">\n");
      out.write("\t\t\t");

			String to_u = request.getParameter("receiver");
		
			//System.out.println(to_u);
			
			if(to_u==null){ 
				out.print("To: <input type=text name=touser>");
				out.print("<input type=hidden name=from_mailbox_userpage value=mailbox>");
			}
			else{
				out.print("To: <input type=hidden name=touser value=" + to_u + ">");
				out.print(to_u);
				out.print("<input type=hidden name=from_mailbox_userpage value=userpage>");
			}
			//To: <input type="text" name="touser"/> <br/>
			
      out.write("\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t    Subject: <input type=\"text\" name=\"Subject\"/> <br/>\n");
      out.write("\t\t    <p>\n");
      out.write("\t\t\t\t<textarea rows=\"10\" cols=\"50\" name=\"Content\"></textarea>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t    \t<input type=\"submit\" value=\"send\"/>\n");
      out.write("\t\t    \t\n");
      out.write("\t\t    </p>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t");

		
		out.println("<div class = \"search-bar\"><p>");
		out.println("Welcome </br>");
		out.println(displayName);
		out.println("</p>");
		out.println("<a href=\"LogoutServlet\" class = \"logout\">Log Out</a>");
		out.println("<form action=\"SearchServlet\" method=\"post\" class =\"search-form\">");
		out.println("<input type=\"text\" name=\"searchKey\" class = \"search\" placeholder = \"Search\"/>");
		out.println("<input type=\"submit\" value=\"H\" class = \"search-button\">");
		out.println("<br>");
		out.println("<input type=\"radio\" name=\"searchType\" value=\"Friend\" checked> <p>Friend</p class = \"search-op\">");
		out.println("<input type=\"radio\" name=\"searchType\" value=\"Quiz\"> <p class = \"search-op\">Quiz</p>");
		out.println("<input type=\"checkbox\" name=\"exactMatch\" value=\"1\"/> <p class = \"search-op\">Exact Match</p>");
		out.println("</form>");
		out.println("</div>");
		
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\n");
      out.write("\t<!-- Bootstrap core JavaScript\n");
      out.write("      ================================================== -->\n");
      out.write("      <!-- Placed at the end of the document so the pages load faster  -->\n");
      out.write("      <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>\n");
      out.write("      <script>\n");
      out.write("\t  $(document).ready(function(){\n");
      out.write("\t\t\t$(\"#M1\").click(function(){\n");
      out.write("\t\t\t\t$(\"#M1-b\").show();\n");
      out.write("\t\t\t\t$(\"#M2-b\").hide();\n");
      out.write("\t\t\t\t$(\"#M3-b\").hide();\t\t\t\t\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t$(\"#M2\").click(function(){\n");
      out.write("\t\t\t\t$(\"#M2-b\").show();\n");
      out.write("\t\t\t\t$(\"#M1-b\").hide();\n");
      out.write("\t\t\t\t$(\"#M3-b\").hide();\t\t\t\t\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t$(\"#M3\").click(function(){\n");
      out.write("\t\t\t\t$(\"#M3-b\").show();\n");
      out.write("\t\t\t\t$(\"#M1-b\").hide();\n");
      out.write("\t\t\t\t$(\"#M2-b\").hide();\t\t\t\t\n");
      out.write("\t\t\t});\n");
      out.write("\t});\n");
      out.write("      </script>\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
