/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-03-14 21:51:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import quiz.*;
import java.text.*;
import database.*;
import java.util.*;

public final class QuizManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");

	List<MyQuiz> allQuiz = QuizHelper.getAllQuiz();

      out.write("\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<table align=\"left\" style=\"width:100%\" border=1>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th><a href=\"admin.jsp\"><font size=4 color=red>Announcement</font></a></th>\n");
      out.write("\t\t\t<th><a href=\"admin-account.jsp\"><font size=4 color=red>Account Manager</font></a></th>\n");
      out.write("\t\t\t<th><a href=\"QuizManagement.jsp\"><font size=4 color=red>Quiz Manager</font></a></th>\n");
      out.write("\t\t\t<th><a href=\"stats.jsp\"><font size=4 color=red>Statistics</font></a></th>\n");
      out.write("\t\t</tr>\n");
      out.write("\t</table>\n");
      out.write("\t<br><br>\n");
      out.write("\n");
      out.write("<form action=\"ModifyQuizServlet\" method=\"post\">\n");


	out.println("<h4> You can delete or clear history of any quiz here: </h4>");
	out.println("<table style=\"width:100%\" align=\"center\" >");
	out.println("<tr>");
	out.println("<th width= \"60%\">Question Name</th>");
	out.println("<th width= \"20%\">Delete Quiz</th>");
	out.println("<th width= \"20%\">Clear History</th>");
	out.println("</tr>");
	
	
	for (int i = 0; i < allQuiz.size(); i++) {
			out.println("<tr>");
			out.println("<td>" + allQuiz.get(i).getQuizName() + "</td>");
			out.println("<td><input type=\"checkbox\" name=\"delete\" value=\"" + allQuiz.get(i).getId() +"\"></td>");
			out.println("<td><input type=\"checkbox\" name=\"clear\" value=\"" + allQuiz.get(i).getId() +"\"></td>");
			out.println("</tr>");
	}
	
	out.println("<tr>");
	out.println("<td> </td>");
	out.println("<td><input type=\"submit\" name=\"button\" value=\"Delete Quiz\"></td>");
	out.println("<td><input type=\"submit\" name=\"button\" value=\"Clear History\"></td>");
	out.println("</tr>");
	
	out.println("</table>");

      out.write("\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<br><br>\n");
      out.write("<a href=\"homepage.jsp\"><font size=4>Home</font></a>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
