/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-03-14 21:39:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import quiz.*;
import java.text.*;
import java.util.List;

public final class QuizResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link rel=\"icon\" href=\"/favicon.ico\">\n");
      out.write("\n");
      out.write("<title>Your Quiz Result</title>\n");
      out.write("<link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<link href=\"./css/style.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
 
String quizID = (String)request.getAttribute("ID");
String username = (String)session.getAttribute("username");
MyQuiz myquiz = new MyQuiz(quizID,1); 
String quizName = myquiz.getQuizName();
MyQuiz.QuizEvent event = myquiz.getUserLatestEvent(quizName, username);

      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"site-wrapper\">\n");
      out.write("      <a href=\"./homepage.jsp\"><div class=\"site-logo\"></div></a>\n");
      out.write("\t \n");
      out.write("\t  \n");
      out.write("\t\t<div class = \"tpanel tpanel-quiz\">\n");
      out.write("\t\t\n");
      out.write("\t\t<ul class = \"quiz-main\">\n");
      out.write("\t\t\t<h2> ");
      out.print(myquiz.getQuizName() );
      out.write(" </h2>\n");
      out.write("\t\t\t<h1> ");
      out.print(event.getScore() );
      out.write('/');
      out.print(myquiz.getTotalScore() );
      out.write(" </h1>\n");
      out.write("\t\t\t<div class = \"low-graph bar-graph\">\n");
      out.write("\t\t\t<div class=\"inner-left-cap\" id = \"user-left-cap\"></div>\n");
      out.write("\t\t\t<div class=\"inner-left-bar\" id = \"user-left\"></div>\n");
      out.write("\t\t\t<div class=\"inner-right-bar\" id = \"user-right\"></div>\n");
      out.write("\t\t\t<div class=\"inner-right-cap\" id = \"user-right-cap\"></div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<ul class = \"graph-table\">\n");
      out.write("\t\t\n");
      out.write("\t\t<li>\n");
      out.write("\t\t<span>Low: ");
      out.print(myquiz.getLowestScore() );
      out.write('/');
      out.print(myquiz.getTotalScore() );
      out.write("</span>\n");
      out.write("\t\t <div class = \"low-graph bar-graph\">\n");
      out.write("\t\t\t<div class=\"inner-left-cap\" id = \"low-left-cap\"></div>\n");
      out.write("\t\t\t<div class=\"inner-left-bar\" id = \"low-left\"></div>\n");
      out.write("\t\t\t<div class=\"inner-right-bar\" id = \"low-right\"></div>\n");
      out.write("\t\t\t<div class=\"inner-right-cap\" id = \"low-right-cap\"></div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</li>\n");
      out.write("\t\t<li>\n");

NumberFormat nf = NumberFormat.getInstance();
nf.setMaximumFractionDigits(0);
nf.setMinimumFractionDigits(0);

      out.write("\n");
      out.write("\t\t<span>Avg: ");
      out.print(nf.format(myquiz.getAvgScore()));
      out.write('/');
      out.print(myquiz.getTotalScore() );
      out.write("</span>\n");
      out.write("\t\t <div class = \"low-graph bar-graph\">\n");
      out.write("\t\t\t<div class=\"inner-left-cap\" id = \"avg-left-cap\"></div>\n");
      out.write("\t\t\t<div class=\"inner-left-bar\" id = \"avg-left\"></div>\n");
      out.write("\t\t\t<div class=\"inner-right-bar\" id = \"avg-right\"></div>\n");
      out.write("\t\t\t<div class=\"inner-right-cap\" id = \"avg-right-cap\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</li>\n");
      out.write("\t\t<li>\n");
      out.write("\t\t<span>High: ");
      out.print(myquiz.getBestScore() );
      out.write('/');
      out.print(myquiz.getTotalScore() );
      out.write("</span>\n");
      out.write("\t\t <div class = \"low-graph bar-graph\">\n");
      out.write("\t\t\t<div class=\"inner-left-cap\" id = \"high-left-cap\"></div>\n");
      out.write("\t\t\t<div class=\"inner-left-bar\" id = \"high-left\"></div>\n");
      out.write("\t\t\t<div class=\"inner-right-bar\" id = \"high-right\"></div>\n");
      out.write("\t\t\t<div class=\"inner-right-cap\" id = \"high-right-cap\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t  <div class = \"cpanel4\">\n");
      out.write("\t\t<div class = \"q_result cpanel-item cpanel-item-quiz\">\n");
      out.write("\t\t<h2> Your Answers</h2>\n");
      out.write("\t\t<h3>Hover for correct answers</h3>\n");
      out.write("\t\t<ol>\n");
      out.write("\t\t");

		List<String> correctAnswer = (List<String>)session.getAttribute("correctAnswer");
		List<String> userAnswer = (List<String>)session.getAttribute("userAnswer"); 
		int size = correctAnswer.size();
		for (int i = 0; i < size; i++) {
			out.println("<li>");
			out.println("<a href=\"#\" class = \"quiz-tag\">");
			out.println(userAnswer.get(i));
			out.println("</a>");
			out.println("<ul>");
			out.println(correctAnswer.get(i));
			out.println("</ul>");
		}
		
		
      out.write("\n");
      out.write("\t\t</ol>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class = \"q_result cpanel-item cpanel-item-quiz\">\n");
      out.write("\t\t<h2> Your Performance </h2>\n");
      out.write("\t\t<div class=\"lpanel lpanel-quiz\">\n");
      out.write("\t\t<div class = \"nav-menu-quiz\">\n");
      out.write("\t\t<ul>\n");
      out.write("          <li id = \"T1b\">\n");
      out.write("              <span class=\"nav-icon-quiz\" id=\"message\">D</span>\n");
      out.write("              <span class=\"nav-title-quiz\">By Date</span>\n");
      out.write("          </li>\n");
      out.write("          <li id = \"T2b\">\n");
      out.write("              <span class=\"nav-icon-quiz\" id=\"quiz\">a</span>\n");
      out.write("              <span class=\"nav-title-quiz\">By Score</span>\n");
      out.write("          </li>\n");
      out.write("          <li id = \"T3b\">\n");
      out.write("             <span class=\"nav-icon-quiz\" id=\"setting\">j</span>\n");
      out.write("              <span class=\"nav-title-quiz\">By Time</span>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("\t  </div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div id = \"T1\" class = \"Tol\">\n");
      out.write("\t\t<p>By Date</p>\n");
      out.write("\t\t<ol>\n");
      out.write("\t\t");

		DateFormat format = new SimpleDateFormat("MM-dd-yy H:mm");
for(MyQuiz.QuizEvent e: myquiz.getUserRecentEvents(username,5)) {
	out.println("<li>" + format.format(e.getSubmitTime()) + ", " + e.getScore() + "/" + myquiz.getTotalScore() + ", " + e.getTimeUsedFormat() + "</li>");
}

      out.write("\n");
      out.write("\t\t</ol>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id = \"T2\" class = \"Tol\">\n");
      out.write("\t\t<p>By Score</p>\n");
      out.write("\t\t<ol>\n");

for(MyQuiz.QuizEvent e: myquiz.getUserRecentScoreEvents(username,5)) {
	out.println("<li>" + format.format(e.getSubmitTime()) + ", " + e.getScore() + "/" + myquiz.getTotalScore() + ", " + e.getTimeUsedFormat() + "</li>");
}

      out.write("\n");
      out.write("\t\t</ol>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div  id = \"T3\" class = \"Tol\">\n");
      out.write("\t\t<p>By Time</p>\n");
      out.write("\t\t<ol>\n");

for(MyQuiz.QuizEvent e: myquiz.getUserRecentTimeEvents(username,5)) {
	out.println("<li>" + format.format(e.getSubmitTime()) + ", " + e.getScore() + "/" + myquiz.getTotalScore() + ", " + e.getTimeUsedFormat() + "</li>");
}

      out.write("\n");
      out.write("\t\t</ol>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class = \"q_result cpanel-item cpanel-item-quiz\">\n");
      out.write("\t\t<h2> Top Performance </h2>\n");
      out.write("\t\t<ol>\n");
      out.write("\t\t");

for(MyQuiz.QuizEvent q: myquiz.getHighScoreEvents(5)) {
	out.println("<li>" + q.getUserName() + " Score: " + q.getScore() + " Time: " + q.getTimeUsedFormat() + "</li>");
}

      out.write("\n");
      out.write("\t\t</ol>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class = \"q_result cpanel-item cpanel-item-quiz\">\n");
      out.write("\t\t<h2> Review </h2>\n");
      out.write("\t\t<p>You can rate and review this quiz:</p>\n");
      out.write("\t\t<form action=\"SaveRateReviewServ\" method=\"post\">\n");
      out.write("\t\t\t<li>Rating<select name=\"rating\">\n");
      out.write("\t\t\t<option value = \"No rating\">No rating</option>\n");
      out.write("\t\t\t<option value = \"0\">0</option>\n");
      out.write("\t\t\t<option value = \"1\">1</option>\n");
      out.write("\t\t\t<option value = \"2\">2</option>\n");
      out.write("\t\t\t<option value = \"3\">3</option>\n");
      out.write("\t\t\t<option value = \"4\">4</option>\n");
      out.write("\t\t\t<option value = \"5\">5</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li>Review<input type=\"text\" name=\"review\" /></li>\n");
      out.write("\t\t\t");
out.println("<input name = quizID type = \"hidden\" value = \"" + quizID + "\"/>"); 
      out.write("\n");
      out.write("\t\t\t<input type=\"submit\" class = \"login-submit\" value=\"Submit\"/>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t  </div>\n");
      out.write("\t   \n");
      out.write("\t  \n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("      <!-- Bootstrap core JavaScript\n");
      out.write("      ================================================== -->\n");
      out.write("      <!-- Placed at the end of the document so the pages load faster  -->\n");
      out.write("      <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>\n");
      out.write("      <script>\n");
      out.write("\t  \n");
      out.write("\t  \n");
      out.write("      $(document).ready(function(){\n");
      out.write("    \t  var total = ");
      out.print(myquiz.getTotalScore());
      out.write(";\n");
      out.write("\t\t\tvar low = ");
      out.print(myquiz.getLowestScore());
      out.write(";\n");
      out.write("\t\t\tvar avg = ");
      out.print(nf.format(myquiz.getAvgScore()));
      out.write(";\n");
      out.write("\t\t\tvar high = ");
      out.print(myquiz.getBestScore());
      out.write(";\n");
      out.write("\t\t\tvar user = ");
      out.print(event.getScore() );
      out.write(";\n");
      out.write("\t\t\tvar lowp = low/total*100;\n");
      out.write("\t\t\tvar avgp = avg/total*100;\n");
      out.write("\t\t\tvar highp = high/total*100;\n");
      out.write("\t\t\tvar userp = user/total*100;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tdocument.getElementById(\"user-left\").style.width = userp*0.98+\"%\";\n");
      out.write("\t\t\tdocument.getElementById(\"user-right\").style.width = (100-userp)*0.98+\"%\";\n");
      out.write("\t\t\tif(user==0){\n");
      out.write("\t\t\t\tdocument.getElementById(\"user-left-cap\").style.background = \"red\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif(user==total){\n");
      out.write("\t\t\t\tdocument.getElementById(\"user-right-cap\").style.background = \"orange\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tdocument.getElementById(\"low-left\").style.width = lowp*0.98+\"%\";\n");
      out.write("\t\t\tdocument.getElementById(\"low-right\").style.width = (100-lowp)*0.98+\"%\";\n");
      out.write("\t\t\tif(low==0){\n");
      out.write("\t\t\t\tdocument.getElementById(\"low-left-cap\").style.background = \"red\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif(low==total){\n");
      out.write("\t\t\t\tdocument.getElementById(\"low-right-cap\").style.background = \"orange\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tdocument.getElementById(\"avg-left\").style.width = avgp*0.98+\"%\";\n");
      out.write("\t\t\tdocument.getElementById(\"avg-right\").style.width = (100-avgp)*0.98+\"%\";\n");
      out.write("\t\t\tif(avg==0){\n");
      out.write("\t\t\t\tdocument.getElementById(\"avg-left-cap\").style.background = \"red\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif(avg==total){\n");
      out.write("\t\t\t\tdocument.getElementById(\"avg-right-cap\").style.background = \"orange\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tdocument.getElementById(\"high-left\").style.width = highp*0.98+\"%\";\n");
      out.write("\t\t\tdocument.getElementById(\"high-right\").style.width = (100-highp)*0.98+\"%\";\n");
      out.write("\t\t\tif(high==0){\n");
      out.write("\t\t\t\tdocument.getElementById(\"high-left-cap\").style.background = \"red\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif(high==total){\n");
      out.write("\t\t\t\tdocument.getElementById(\"high-right-cap\").style.background = \"orange\";\n");
      out.write("\t\t\t}\n");
      out.write("  \t\t$(\"#T1b\").click(function() {\n");
      out.write("  \t\t\t$(\"#T1\").show();\n");
      out.write("  \t\t\t$(\"#T2\").hide();\n");
      out.write("  \t\t\t$(\"#T3\").hide();\n");
      out.write("  \t\t});\n");
      out.write("  \t\t$(\"#T2b\").click(function() {\n");
      out.write("  \t\t\t$(\"#T2\").show();\n");
      out.write("  \t\t\t$(\"#T1\").hide();\n");
      out.write("  \t\t\t$(\"#T3\").hide();\n");
      out.write("  \t\t});\n");
      out.write("  \t\t$(\"#T3b\").click(function() {\n");
      out.write("  \t\t\t$(\"#T3\").show();\n");
      out.write("  \t\t\t$(\"#T1\").hide();\n");
      out.write("  \t\t\t$(\"#T2\").hide();\n");
      out.write("  \t\t});\t\t\n");
      out.write("  \t\t})\n");
      out.write("      </script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
