/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-03-14 21:33:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String signupErrMsg = (String) session.getAttribute("signupErrMsg");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <link rel=\"icon\" href=\"/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <title>Quiz</title>\r\n");
      out.write("    <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"./css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"site-wrapper\">\r\n");
      out.write("      <a href=\"homepage.jsp\"><div class=\"site-logo\"></div></a>\r\n");
      out.write("<div class = \"easy-b\">\r\n");
      out.write("\t<h1>Create New Account</h1>\r\n");
      out.write("\t<form action=\"SignupServlet\" method=\"post\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>Username: <input type=\"text\" name=\"username\" />  \r\n");
      out.write("\t\t\t");

			if(signupErrMsg != null){
				out.print(signupErrMsg);
				session.removeAttribute("signupErrMsg");
			}
			
      out.write("\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>Password: <input type=\"password\" name=\"password\" /> </li>\r\n");
      out.write("\t\t\t<li>Name to be displayed: <input type=\"text\" name=\"displayname\" /> </li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<h2>Privacy Setting:</h2>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>  Who can see my quiz taking history: \r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"privacy_quiz_take\" value=\"0\" checked/> Myself\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"privacy_quiz_take\" value=\"1\"/> My friends\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"privacy_quiz_take\" value=\"3\"/> Everyone \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>  Who can see my quiz creating history: \r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"privacy_quiz_create\" value=\"0\" checked/> Myself\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"privacy_quiz_create\" value=\"1\"/> My friends\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"privacy_quiz_create\" value=\"3\"/> Everyone \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>  Who can see my quiz scores: \r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"privacy_quiz_score\" value=\"0\" checked/> Myself\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"privacy_quiz_score\" value=\"1\"/> My friends\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"privacy_quiz_score\" value=\"3\"/> Everyone \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>  Who can see my achievements: \r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"privacy_achieve\" value=\"0\" checked/> Myself\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"privacy_achieve\" value=\"1\"/> My friends\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"privacy_achieve\" value=\"3\"/> Everyone \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Sign Up\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
